### ISSUE TITLE
Removed from Google Play?

### ISSUE THREAD

**Issue by BobQuentok** [vocollapse/Blockinger#3]
I can't find your app in Google Play anymore. What happened?

**Comment by unforgettableid** [comment]
@vocollapse: Have you had any luck re-releasing this on the Google Play store?

P.S.  Thank you very much for writing the game and releasing it as open-source!

**Comment by unforgettableid** [comment]
Is this it?  https://play.google.com/store/apps/details?id=iapp.blockinger.game
